[tool.poetry]
name = "notification-svc-business-rules"
version = "0.1.0"
description = ""
authors = ["Lucas <lucassrod@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
